//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 22/03/2012
//  @ Author : 
//
//

package modelos;

public class Cliente {
	private String dni;
	private String nombre;
	private String apellido;
        private String tipoCliente;
        private double numeroPuntos;

       
    public Cliente(String dni, String nombre, String apellido, String tipoCliente, double numeroPuntos) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido = apellido;
        this.tipoCliente = tipoCliente;
        this.numeroPuntos = numeroPuntos;
    }

    public double getNumeroPuntos() {
        return numeroPuntos;
    }

    public String getTipoCliente() {
        return tipoCliente;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
