//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 22/03/2012
//  @ Author : 
//
//

package modelos;

public class Factura {
	private String dni;
	private String numeroFactura;
        private String fecha;
	private Double montoVenta;

    public Factura(String dni, String numeroFactura, String fecha, Double montoVenta) {
        this.dni = dni;
        this.numeroFactura = numeroFactura;
        this.fecha = fecha;
        this.montoVenta = montoVenta;
    }

    public String getDni() {
        return dni;
    }

    public String getFecha() {
        return fecha;
    }

    public Double getMontoVenta() {
        return montoVenta;
    }

    public String getNumeroFactura() {
        return numeroFactura;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public void setMontoVenta(Double montoVenta) {
        this.montoVenta = montoVenta;
    }

    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }

    
}
