//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoCliente.java
//  @ Date : 22/03/2012
//  @ Author : 
//
//




public class TipoCliente {
	private Double montoAcumulado;
	private String tipoCliente;
}
